# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ba6369cd33b2060cd100e1812078aa311cd3a81af96f7b27e77308054a5a9ca4dcea5c5bd7157efb3daf486de63bf06b2607d7c824b2a70b674f2f4dd06198a

test:
  secret_key_base: 537ad8bbddf59ace8ea4362a5993a7abaa1d616bb1b1f325e6c78847ba69ec359fc29322e41c16e72469c70cc1c9de0c56be71cb87aea4ce29bd20e55173d813

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
