# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55cc0f4e001d9566c626511059f828146a837cc711b1152d1295564d739edaaff1426608799c260653e9cbe24589a588a5b5959c9278250eb711ba19e2603154

test:
  secret_key_base: eacaa59aa458750eaf63656ed4749a8627dd89a79ae5d0fb016eec6d99bfef828e12d5fae7fd9e4a061996d953d54356dc67503f313480838724808845c9f5f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
